sudo: false
language: python
python: 
- '3.4'
- '3.5'
install:
- pip install tornado

before_script:
- export ACCESS_KEY="CKQNXugLAXFueA5UlBKQnkWxslYC8rIErwn2ch4I"
- export SECRET_KEY="4lnKaSKUk1SVmbB4alt6PtkL2O1Sm-jP6e-T7EER"
- export DOMAIN="7xs7oc.com1.z0.glb.clouddn.com"
- export BUCKET="static-pyblog-com"

	
