sudo: false
language: python
python: 
- '3.4'
- '3.5'
install:
- pip install tornado
- pip install autopep8
- pip install flake8
before_script:
- export ACCESS_KEY="CKQNXugLAXFueA5UlBKQnkWxslYC8rIErwn2ch4I"
- export SECRET_KEY="4lnKaSKUk1SVmbB4alt6PtkL2O1Sm-jP6e-T7EER"
- export DOMAIN="7xs7oc.com1.z0.glb.clouddn.com"
- export BUCKET="static-pyblog-com"
- PYTHONPATH="$PYTHONPATH:."
script:
- flask8 --show-source --show-pep8 --max-line-length=160
- python -m tornaqiniu.tests.runtests
